import type { Report } from "./types";

// Seed rows pre-date the fatality_count column. Each row's status is the
// row's worst outcome (no per-row aggregation across outcomes), so deriving
// fatality_count from status preserves the methodology's principle #2 without
// hand-editing 25 rows. New aggregated rows (Pattern A in §4.2) must set
// fatality_count explicitly via the DB.
type RawSeed = Omit<Report, "fatality_count">;

const rawSeedReports: RawSeed[] = [
  {
    kind: "confirmed",
    id: "rpt_001",
    lat: 33.4484,
    lng: -112.074,
    location_name: "Phoenix",
    state_province: "Arizona",
    country: "United States",
    status: "confirmed",
    severity: "moderate",
    reported_date: "2026-04-28",
    source_name: "Arizona Department of Health Services",
    source_url: "https://www.azdhs.gov/",
    case_count: 47,
    notes:
      "Cluster of vector-borne illness reported in Maricopa County following extended monsoon season. Public advisory issued.",
    condition: "Vector-borne (suspected West Nile)",
  },
  {
    kind: "confirmed",
    id: "rpt_002",
    lat: 36.1699,
    lng: -115.1398,
    location_name: "Las Vegas",
    state_province: "Nevada",
    country: "United States",
    status: "suspected",
    severity: "low",
    reported_date: "2026-05-01",
    source_name: "Southern Nevada Health District",
    source_url: "https://www.snhd.info/",
    case_count: 12,
    notes:
      "Suspected respiratory cluster among hospitality workers. Awaiting laboratory confirmation.",
    condition: "Respiratory illness",
  },
  {
    kind: "confirmed",
    id: "rpt_003",
    lat: 35.0844,
    lng: -106.6504,
    location_name: "Albuquerque",
    state_province: "New Mexico",
    country: "United States",
    status: "confirmed",
    severity: "high",
    reported_date: "2026-04-22",
    source_name: "New Mexico Department of Health",
    source_url: "https://www.nmhealth.org/",
    case_count: 89,
    notes:
      "Confirmed gastrointestinal outbreak linked to municipal water system in central neighborhoods. Boil-water advisory active.",
    condition: "Gastrointestinal",
  },
  {
    kind: "confirmed",
    id: "rpt_004",
    lat: 32.7157,
    lng: -117.1611,
    location_name: "San Diego",
    state_province: "California",
    country: "United States",
    status: "reported",
    severity: "low",
    reported_date: "2026-05-04",
    source_name: "San Diego County Public Health",
    case_count: 6,
    notes: "Sporadic reports of seasonal influenza variant, low severity.",
    condition: "Influenza-like illness",
  },
  {
    kind: "confirmed",
    id: "rpt_005",
    lat: 31.7619,
    lng: -106.485,
    location_name: "El Paso",
    state_province: "Texas",
    country: "United States",
    status: "suspected",
    severity: "moderate",
    reported_date: "2026-04-30",
    source_name: "Texas DSHS",
    case_count: 23,
    notes:
      "Suspected cross-border respiratory cluster, samples sent to state lab for sequencing.",
    condition: "Respiratory illness",
  },
  {
    kind: "confirmed",
    id: "rpt_006",
    lat: -12.0464,
    lng: -77.0428,
    location_name: "Lima",
    country: "Peru",
    status: "confirmed",
    severity: "high",
    reported_date: "2026-04-18",
    source_name: "Ministerio de Salud del Perú",
    source_url: "https://www.gob.pe/minsa",
    case_count: 312,
    notes:
      "Dengue outbreak ongoing in coastal districts; vector control operations underway.",
    condition: "Dengue",
  },
  {
    kind: "confirmed",
    id: "rpt_007",
    lat: -33.4489,
    lng: -70.6693,
    location_name: "Santiago",
    country: "Chile",
    status: "reported",
    severity: "low",
    reported_date: "2026-05-02",
    source_name: "Ministerio de Salud de Chile",
    case_count: 18,
    notes:
      "Routine surveillance flagged minor uptick in respiratory presentations among children under 5.",
    condition: "Respiratory illness",
  },
  {
    kind: "confirmed",
    id: "rpt_008",
    lat: -34.6037,
    lng: -58.3816,
    location_name: "Buenos Aires",
    country: "Argentina",
    status: "suspected",
    severity: "moderate",
    reported_date: "2026-04-26",
    source_name: "Ministerio de Salud Argentina",
    case_count: 54,
    notes:
      "Suspected hantavirus cases reported from peri-urban districts; investigation in progress.",
    condition: "Hantavirus (suspected)",
  },
  {
    kind: "confirmed",
    id: "rpt_009",
    lat: -23.5505,
    lng: -46.6333,
    location_name: "São Paulo",
    country: "Brazil",
    status: "confirmed",
    severity: "high",
    reported_date: "2026-04-15",
    source_name: "Ministério da Saúde",
    source_url: "https://www.gov.br/saude/",
    case_count: 1487,
    notes:
      "Confirmed dengue surge across metropolitan region; emergency vector control deployed.",
    condition: "Dengue",
  },
  {
    kind: "confirmed",
    id: "rpt_010",
    lat: 4.711,
    lng: -74.0721,
    location_name: "Bogotá",
    country: "Colombia",
    status: "confirmed",
    severity: "moderate",
    reported_date: "2026-04-29",
    source_name: "Instituto Nacional de Salud",
    case_count: 67,
    notes:
      "Confirmed leptospirosis cluster following heavy rainfall and flooding in southern localities.",
    condition: "Leptospirosis",
  },
  {
    kind: "confirmed",
    id: "rpt_011",
    lat: 51.5074,
    lng: -0.1278,
    location_name: "London",
    country: "United Kingdom",
    status: "reported",
    severity: "low",
    reported_date: "2026-05-03",
    source_name: "UK Health Security Agency",
    source_url: "https://www.gov.uk/government/organisations/uk-health-security-agency",
    case_count: 9,
    notes:
      "Small cluster of measles reported in school-aged children; public health response activated.",
    condition: "Measles",
  },
  {
    kind: "confirmed",
    id: "rpt_012",
    lat: 48.8566,
    lng: 2.3522,
    location_name: "Paris",
    country: "France",
    status: "confirmed",
    severity: "moderate",
    reported_date: "2026-04-24",
    source_name: "Santé publique France",
    case_count: 34,
    notes:
      "Confirmed legionellosis cluster linked to a cooling tower in the 13th arrondissement.",
    condition: "Legionellosis",
  },
  {
    kind: "confirmed",
    id: "rpt_013",
    lat: 52.52,
    lng: 13.405,
    location_name: "Berlin",
    country: "Germany",
    status: "suspected",
    severity: "low",
    reported_date: "2026-05-01",
    source_name: "Robert Koch-Institut",
    source_url: "https://www.rki.de/",
    case_count: 21,
    notes:
      "Suspected foodborne gastroenteritis at a public event; investigations ongoing.",
    condition: "Gastrointestinal",
  },
  {
    kind: "confirmed",
    id: "rpt_014",
    lat: 41.9028,
    lng: 12.4964,
    location_name: "Rome",
    country: "Italy",
    status: "reported",
    severity: "low",
    reported_date: "2026-04-27",
    source_name: "Ministero della Salute",
    case_count: 14,
    notes:
      "Tick-borne encephalitis reports trending up in Lazio region; advisory issued for hikers.",
    condition: "Tick-borne",
  },
  {
    kind: "confirmed",
    id: "rpt_015",
    lat: 40.4168,
    lng: -3.7038,
    location_name: "Madrid",
    country: "Spain",
    status: "confirmed",
    severity: "moderate",
    reported_date: "2026-04-20",
    source_name: "Ministerio de Sanidad",
    case_count: 58,
    notes:
      "Confirmed pertussis outbreak in school district; vaccination clinics extended hours.",
    condition: "Pertussis",
  },
  {
    kind: "confirmed",
    id: "rpt_016",
    lat: 37.9838,
    lng: 23.7275,
    location_name: "Athens",
    country: "Greece",
    status: "resolved",
    severity: "low",
    reported_date: "2026-04-05",
    source_name: "Hellenic National Public Health Organization",
    case_count: 11,
    notes:
      "Foodborne salmonella outbreak resolved; source traced to a single catering vendor.",
    condition: "Salmonellosis",
  },
  {
    kind: "confirmed",
    id: "rpt_017",
    lat: 35.6762,
    lng: 139.6503,
    location_name: "Tokyo",
    country: "Japan",
    status: "confirmed",
    severity: "moderate",
    reported_date: "2026-04-25",
    source_name: "Japan National Institute of Infectious Diseases",
    source_url: "https://www.niid.go.jp/",
    case_count: 142,
    notes:
      "Confirmed seasonal influenza B activity above baseline in greater Tokyo region.",
    condition: "Influenza B",
  },
  {
    kind: "confirmed",
    id: "rpt_018",
    lat: 37.5665,
    lng: 126.978,
    location_name: "Seoul",
    country: "South Korea",
    status: "reported",
    severity: "low",
    reported_date: "2026-05-02",
    source_name: "Korea Disease Control and Prevention Agency",
    source_url: "https://www.kdca.go.kr/",
    case_count: 19,
    notes:
      "Reports of mild gastrointestinal illness among university dormitory residents under investigation.",
    condition: "Gastrointestinal",
  },
  {
    kind: "confirmed",
    id: "rpt_019",
    lat: 31.2304,
    lng: 121.4737,
    location_name: "Shanghai",
    country: "China",
    status: "suspected",
    severity: "moderate",
    reported_date: "2026-04-29",
    source_name: "Chinese Center for Disease Control and Prevention",
    case_count: 73,
    notes:
      "Suspected hand-foot-and-mouth disease cluster in early childhood centers.",
    condition: "Hand-foot-and-mouth",
  },
  {
    kind: "confirmed",
    id: "rpt_020",
    lat: 22.3193,
    lng: 114.1694,
    location_name: "Hong Kong",
    country: "Hong Kong SAR",
    status: "confirmed",
    severity: "moderate",
    reported_date: "2026-04-21",
    source_name: "Centre for Health Protection",
    source_url: "https://www.chp.gov.hk/",
    case_count: 41,
    notes:
      "Confirmed scarlet fever uptick; advisories distributed to schools and clinics.",
    condition: "Scarlet fever",
  },
  {
    kind: "confirmed",
    id: "rpt_021",
    lat: 1.3521,
    lng: 103.8198,
    location_name: "Singapore",
    country: "Singapore",
    status: "confirmed",
    severity: "high",
    reported_date: "2026-04-19",
    source_name: "Ministry of Health Singapore",
    source_url: "https://www.moh.gov.sg/",
    case_count: 218,
    notes:
      "Confirmed dengue outbreak with multiple active clusters; mosquito eradication ongoing.",
    condition: "Dengue",
  },
  {
    kind: "confirmed",
    id: "rpt_022",
    lat: 14.5995,
    lng: 120.9842,
    location_name: "Manila",
    country: "Philippines",
    status: "confirmed",
    severity: "high",
    reported_date: "2026-04-23",
    source_name: "Department of Health Philippines",
    case_count: 376,
    notes:
      "Confirmed leptospirosis spike post-flooding; emergency response active across Metro Manila.",
    condition: "Leptospirosis",
  },
  {
    kind: "confirmed",
    id: "rpt_023",
    lat: 13.7563,
    lng: 100.5018,
    location_name: "Bangkok",
    country: "Thailand",
    status: "suspected",
    severity: "moderate",
    reported_date: "2026-05-01",
    source_name: "Department of Disease Control Thailand",
    source_url: "https://ddc.moph.go.th/",
    case_count: 64,
    notes:
      "Suspected chikungunya activity reported in northern districts; vector surveillance increased.",
    condition: "Chikungunya",
  },
  {
    kind: "confirmed",
    id: "rpt_024",
    lat: -6.2088,
    lng: 106.8456,
    location_name: "Jakarta",
    country: "Indonesia",
    status: "reported",
    severity: "moderate",
    reported_date: "2026-04-30",
    source_name: "Ministry of Health Indonesia",
    case_count: 132,
    notes:
      "Reports of dengue and typhoid co-circulation following monsoon season.",
    condition: "Dengue / Typhoid",
  },
  {
    kind: "confirmed",
    id: "rpt_025",
    lat: 32.0853,
    lng: 34.7818,
    location_name: "Tel Aviv",
    country: "Israel",
    status: "resolved",
    severity: "low",
    reported_date: "2026-04-08",
    source_name: "Israel Ministry of Health",
    case_count: 16,
    notes:
      "Foodborne salmonella event resolved after recall of contaminated product.",
    condition: "Salmonellosis",
  },
];

export const seedReports: Report[] = rawSeedReports.map((r) => ({
  ...r,
  fatality_count: r.status === "fatal" ? r.case_count : 0,
}));
